-- Hand-written follow-up migration (not generated by drizzle-kit).
--
-- Converts the high-frequency time-series tables into TimescaleDB
-- hypertables: `market_ticks`, `orderbook_snapshots`, and `trades`. These
-- are the tables the market-stream service writes to on every tick/book
-- update/trade, per CLAUDE.md section 11 (market data pipeline) and section
-- 71 (data retention -- "retain high-frequency tick data for a configurable
-- retention period, aggregate longer term").
--
-- Hypertables automatically partition by the `timestamp` column into
-- per-interval chunks, which keeps inserts and time-range queries fast as
-- these tables grow, and makes retention/aggregation policies (e.g.
-- `add_retention_policy`, continuous aggregates for 1m/5m/15m/1h/1d
-- rollups) straightforward to add later without touching application code.
--
-- Requires the `timescaledb` extension. Run this against a TimescaleDB-
-- enabled Postgres instance (e.g. `timescale/timescaledb-ha` or AWS RDS's
-- Timescale-compatible setup per CLAUDE.md section 8) after running the
-- drizzle-kit-generated `0000_*.sql` migration that creates these tables.
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- `if_not_exists => TRUE` makes this migration safe to re-run.
SELECT create_hypertable('market_ticks', 'timestamp', if_not_exists => TRUE);
SELECT create_hypertable('orderbook_snapshots', 'timestamp', if_not_exists => TRUE);
SELECT create_hypertable('trades', 'timestamp', if_not_exists => TRUE);
